_wandb:
    value:
        cli_version: 0.21.4
        code_path: code/scripts/train.py
        e:
            o46p2fdr3nk5uz8ivid1hg1siwbukhbp:
                codePath: scripts/train.py
                codePathLocal: scripts/train.py
                email: guillaume.corlouer@gmail.com
                executable: /Users/guime/anaconda3/envs/dln-sgd/bin/python
                git:
                    commit: 9e565ef60a8efbab5cc29dd7e6f6e9f5c12a01a0
                    remote: git@github.com:gcorlouer/sgd_dlns.git
                host: Guillaumes-MBP.SafeAI-Sec.local
                os: macOS-14.2.1-arm64-arm-64bit
                program: /Users/guime/projects/bias_sgd/sgd_dlns_code/scripts/train.py
                python: CPython 3.12.11
                root: /Users/guime/projects/bias_sgd/sgd_dlns_code
                startedAt: "2025-09-22T11:25:57.107093Z"
                writerId: o46p2fdr3nk5uz8ivid1hg1siwbukhbp
        m: []
        python_version: 3.12.11
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.12.11
            "5": 0.21.4
            "12": 0.21.4
            "13": darwin-arm64
